//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdicionalesPyP
    {
        public int RowID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> OperacionID { get; set; }
        public Nullable<System.DateTime> FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public string HoraLlegada { get; set; }
        public string HoraSalida { get; set; }
        public Nullable<int> TipoPosicionLlegadaID { get; set; }
        public Nullable<int> TipoPosicionSalidaID { get; set; }
        public Nullable<int> TipoLlegadaID { get; set; }
        public Nullable<int> PosicionLlegadaID { get; set; }
        public Nullable<int> PosicionSalidaID { get; set; }
        public Nullable<bool> Despego { get; set; }
        public string HoraDespegue { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public string HoraLlegadaPuente { get; set; }
        public string HoraSalidaPuente { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Operacion Operacion { get; set; }
        public virtual Tipo Tipo { get; set; }
        public virtual Tipo Tipo1 { get; set; }
        public virtual Tipo Tipo2 { get; set; }
        public virtual Tipo Tipo3 { get; set; }
        public virtual Tipo Tipo4 { get; set; }
    }
}
