//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeropuerto
    {
        public Aeropuerto()
        {
            this.Llegada = new HashSet<Llegada>();
            this.Planeacion = new HashSet<Planeacion>();
            this.Planeacion1 = new HashSet<Planeacion>();
            this.Salida = new HashSet<Salida>();
        }
    
        public int RowID { get; set; }
        public string Nombre { get; set; }
        public string SiglaIATA { get; set; }
        public string SiglaOACI { get; set; }
        public string Pais { get; set; }
        public string Ciudad { get; set; }
        public Nullable<int> TipoAeropuertoID { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual ICollection<Llegada> Llegada { get; set; }
        public virtual ICollection<Planeacion> Planeacion { get; set; }
        public virtual ICollection<Planeacion> Planeacion1 { get; set; }
        public virtual ICollection<Salida> Salida { get; set; }
    }
}
