//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeronave
    {
        public Aeronave()
        {
            this.Operacion = new HashSet<Operacion>();
        }
    
        public int RowID { get; set; }
        public string Matricula { get; set; }
        public Nullable<int> ClasificacionID { get; set; }
        public Nullable<int> PropietarioID { get; set; }
        public Nullable<int> CompañiaFacturaID { get; set; }
        public Nullable<int> PBMOKG { get; set; }
        public Nullable<System.DateTime> FechaVencimientoMatricula { get; set; }
        public string TipoAeronave { get; set; }
        public Nullable<int> CapacidadPasajeros { get; set; }
        public Nullable<bool> PermisoExplotacion { get; set; }
        public Nullable<bool> Extranjera { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Tipo Tipo { get; set; }
        public virtual Tercero Tercero { get; set; }
        public virtual Tercero Tercero1 { get; set; }
        public virtual ICollection<Operacion> Operacion { get; set; }
    }
}
