//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bombero
    {
        public int RowID { get; set; }
        public Nullable<int> OperacionID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> TipoServicioBombID { get; set; }
        public Nullable<double> ValorServicio { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Operacion Operacion { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
