//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wmsEntities : DbContext
    {
        public wmsEntities()
            : base("name=wmsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aeronave> Aeronave { get; set; }
        public DbSet<Aeropuerto> Aeropuerto { get; set; }
        public DbSet<Bombero> Bombero { get; set; }
        public DbSet<Llegada> Llegada { get; set; }
        public DbSet<Operacion> Operacion { get; set; }
        public DbSet<Planeacion> Planeacion { get; set; }
        public DbSet<Salida> Salida { get; set; }
        public DbSet<TarifaCecoa> TarifaCecoa { get; set; }
        public DbSet<Compañia> Compañia { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<MenuRol> MenuRol { get; set; }
        public DbSet<Agrupacion> Agrupacion { get; set; }
        public DbSet<Conexion> Conexion { get; set; }
        public DbSet<Configuracion> Configuracion { get; set; }
        public DbSet<Estado> Estado { get; set; }
        public DbSet<Tercero> Tercero { get; set; }
        public DbSet<Tipo> Tipo { get; set; }
        public DbSet<TRM> TRM { get; set; }
        public DbSet<Rol> Rol { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
