//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estado
    {
        public Estado()
        {
            this.Bombero = new HashSet<Bombero>();
            this.Llegada = new HashSet<Llegada>();
            this.Operacion = new HashSet<Operacion>();
            this.Salida = new HashSet<Salida>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> TipoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<Bombero> Bombero { get; set; }
        public virtual ICollection<Llegada> Llegada { get; set; }
        public virtual ICollection<Operacion> Operacion { get; set; }
        public virtual ICollection<Salida> Salida { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
