//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Llegada
    {
        public Llegada()
        {
            this.Operacion = new HashSet<Operacion>();
        }
    
        public int RowID { get; set; }
        public string NVuelo { get; set; }
        public string HoraProgramadaLlegada { get; set; }
        public string HoraAterrizaje { get; set; }
        public string HoraPlataforma { get; set; }
        public string HoraPuente { get; set; }
        public Nullable<System.DateTime> FechaAterrizaje { get; set; }
        public Nullable<System.DateTime> FechaLLegadaPlataforma { get; set; }
        public Nullable<System.DateTime> FechaLlegadaPuente { get; set; }
        public Nullable<int> TipoPosicionID { get; set; }
        public Nullable<int> PosicionID { get; set; }
        public Nullable<int> TipoDeclaracionID { get; set; }
        public Nullable<int> TipoVueloID { get; set; }
        public Nullable<int> BandaID { get; set; }
        public Nullable<double> CargaEntrada { get; set; }
        public Nullable<double> CorreoEntrada { get; set; }
        public Nullable<int> CantPax { get; set; }
        public Nullable<int> Sala { get; set; }
        public Nullable<int> ClasificacionID { get; set; }
        public Nullable<int> CIAFacturaID { get; set; }
        public Nullable<int> OrigenID { get; set; }
        public string Observaciones { get; set; }
        public int EstadoID { get; set; }
        public Nullable<System.DateTime> FechaProgramacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual Tipo Tipo { get; set; }
        public virtual Tercero Tercero { get; set; }
        public virtual Tipo Tipo1 { get; set; }
        public virtual Tipo Tipo2 { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Tipo Tipo3 { get; set; }
        public virtual Tipo Tipo4 { get; set; }
        public virtual Tipo Tipo5 { get; set; }
        public virtual ICollection<Operacion> Operacion { get; set; }
    }
}
