//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public Operacion()
        {
            this.Bombero = new HashSet<Bombero>();
            this.Servicios = new HashSet<Servicios>();
            this.Tasas = new HashSet<Tasas>();
            this.AdicionalesPyP = new HashSet<AdicionalesPyP>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> TipoFacturacionID { get; set; }
        public Nullable<int> AeronaveID { get; set; }
        public int LlegadaID { get; set; }
        public Nullable<int> SalidaID { get; set; }
        public System.DateTime FechaOP { get; set; }
        public Nullable<System.DateTime> FechaAnulado { get; set; }
        public Nullable<int> EstadoID { get; set; }
        public Nullable<bool> Facturado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Aeronave Aeronave { get; set; }
        public virtual ICollection<Bombero> Bombero { get; set; }
        public virtual Llegada Llegada { get; set; }
        public virtual Salida Salida { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Tipo Tipo { get; set; }
        public virtual ICollection<Servicios> Servicios { get; set; }
        public virtual ICollection<Tasas> Tasas { get; set; }
        public virtual ICollection<AdicionalesPyP> AdicionalesPyP { get; set; }
    }
}
