//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planeacion
    {
        public int RowID { get; set; }
        public Nullable<int> CompaniaID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string NVueloEntrada { get; set; }
        public string NVueloSalida { get; set; }
        public string HoraEntrada { get; set; }
        public string HoraSalida { get; set; }
        public string Stand { get; set; }
        public Nullable<int> Sala { get; set; }
        public string TipoAeronave { get; set; }
        public Nullable<int> BandaID { get; set; }
        public Nullable<int> OrigenID { get; set; }
        public Nullable<int> DestinoID { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual Aeropuerto Aeropuerto1 { get; set; }
        public virtual Tipo Tipo { get; set; }
        public virtual Tercero Tercero { get; set; }
    }
}
