//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida
    {
        public Salida()
        {
            this.Operacion = new HashSet<Operacion>();
        }
    
        public int RowID { get; set; }
        public string NVueloSalida { get; set; }
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public string HoraProgramadaSalida { get; set; }
        public string HoraSalidaPuente { get; set; }
        public string HoraSalidaPlataforma { get; set; }
        public string HoraDespegue { get; set; }
        public Nullable<System.DateTime> FechaSalidaPuente { get; set; }
        public Nullable<System.DateTime> FechaSalidaPlataforma { get; set; }
        public Nullable<System.DateTime> FechaDespegue { get; set; }
        public Nullable<int> TipoPosicionSalidaID { get; set; }
        public Nullable<int> PosicionSalidaID { get; set; }
        public Nullable<int> TipoVueloSalidaID { get; set; }
        public Nullable<int> DestinoID { get; set; }
        public Nullable<double> CargaSalida { get; set; }
        public Nullable<double> CorreoSalida { get; set; }
        public string HoraSalidaPuenteReal { get; set; }
        public string HoraSalidaPlataformaReal { get; set; }
        public string HoraDespegueReal { get; set; }
        public int EstadoID { get; set; }
        public Nullable<int> Sala { get; set; }
        public Nullable<System.DateTime> FechaProgramacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual Aeropuerto Aeropuerto { get; set; }
        public virtual ICollection<Operacion> Operacion { get; set; }
        public virtual Tipo Tipo { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Tipo Tipo1 { get; set; }
        public virtual Tipo Tipo2 { get; set; }
    }
}
