//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tercero
    {
        public Tercero()
        {
            this.Aeronave = new HashSet<Aeronave>();
            this.Aeronave1 = new HashSet<Aeronave>();
            this.Llegada = new HashSet<Llegada>();
            this.Planeacion = new HashSet<Planeacion>();
        }
    
        public int RowID { get; set; }
        public Nullable<long> Identificacion { get; set; }
        public Nullable<int> Digito { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> TipoTerceroID { get; set; }
        public Nullable<bool> Sincronizado { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<Aeronave> Aeronave { get; set; }
        public virtual ICollection<Aeronave> Aeronave1 { get; set; }
        public virtual ICollection<Llegada> Llegada { get; set; }
        public virtual ICollection<Planeacion> Planeacion { get; set; }
        public virtual Tipo Tipo { get; set; }
    }
}
