//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfFront.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo
    {
        public Tipo()
        {
            this.Aeronave = new HashSet<Aeronave>();
            this.Aeropuerto = new HashSet<Aeropuerto>();
            this.Bombero = new HashSet<Bombero>();
            this.Llegada = new HashSet<Llegada>();
            this.Llegada1 = new HashSet<Llegada>();
            this.Llegada2 = new HashSet<Llegada>();
            this.Llegada3 = new HashSet<Llegada>();
            this.Llegada4 = new HashSet<Llegada>();
            this.Llegada5 = new HashSet<Llegada>();
            this.Operacion = new HashSet<Operacion>();
            this.Planeacion = new HashSet<Planeacion>();
            this.Salida = new HashSet<Salida>();
            this.Salida1 = new HashSet<Salida>();
            this.Salida2 = new HashSet<Salida>();
            this.TarifaCecoa = new HashSet<TarifaCecoa>();
            this.TarifaCecoa1 = new HashSet<TarifaCecoa>();
            this.Menu = new HashSet<Menu>();
            this.Conexion = new HashSet<Conexion>();
            this.Estado = new HashSet<Estado>();
            this.Tercero = new HashSet<Tercero>();
            this.Facturas = new HashSet<Facturas>();
            this.Servicios = new HashSet<Servicios>();
            this.Tasas = new HashSet<Tasas>();
            this.AdicionalesPyP = new HashSet<AdicionalesPyP>();
            this.AdicionalesPyP1 = new HashSet<AdicionalesPyP>();
            this.AdicionalesPyP2 = new HashSet<AdicionalesPyP>();
            this.AdicionalesPyP3 = new HashSet<AdicionalesPyP>();
            this.AdicionalesPyP4 = new HashSet<AdicionalesPyP>();
        }
    
        public int RowID { get; set; }
        public Nullable<int> AgrupacionID { get; set; }
        public string Codigo { get; set; }
        public string Codigo2 { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Valor { get; set; }
        public Nullable<int> Orden { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioModificacion { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
    
        public virtual ICollection<Aeronave> Aeronave { get; set; }
        public virtual ICollection<Aeropuerto> Aeropuerto { get; set; }
        public virtual ICollection<Bombero> Bombero { get; set; }
        public virtual ICollection<Llegada> Llegada { get; set; }
        public virtual ICollection<Llegada> Llegada1 { get; set; }
        public virtual ICollection<Llegada> Llegada2 { get; set; }
        public virtual ICollection<Llegada> Llegada3 { get; set; }
        public virtual ICollection<Llegada> Llegada4 { get; set; }
        public virtual ICollection<Llegada> Llegada5 { get; set; }
        public virtual ICollection<Operacion> Operacion { get; set; }
        public virtual ICollection<Planeacion> Planeacion { get; set; }
        public virtual ICollection<Salida> Salida { get; set; }
        public virtual ICollection<Salida> Salida1 { get; set; }
        public virtual ICollection<Salida> Salida2 { get; set; }
        public virtual ICollection<TarifaCecoa> TarifaCecoa { get; set; }
        public virtual ICollection<TarifaCecoa> TarifaCecoa1 { get; set; }
        public virtual ICollection<Menu> Menu { get; set; }
        public virtual Agrupacion Agrupacion { get; set; }
        public virtual ICollection<Conexion> Conexion { get; set; }
        public virtual ICollection<Estado> Estado { get; set; }
        public virtual ICollection<Tercero> Tercero { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<Servicios> Servicios { get; set; }
        public virtual ICollection<Tasas> Tasas { get; set; }
        public virtual ICollection<AdicionalesPyP> AdicionalesPyP { get; set; }
        public virtual ICollection<AdicionalesPyP> AdicionalesPyP1 { get; set; }
        public virtual ICollection<AdicionalesPyP> AdicionalesPyP2 { get; set; }
        public virtual ICollection<AdicionalesPyP> AdicionalesPyP3 { get; set; }
        public virtual ICollection<AdicionalesPyP> AdicionalesPyP4 { get; set; }
    }
}
